# Generated by Django 3.2.7 on 2025-10-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='roomNumber',
            field=models.IntegerField(default=11, max_length=100),
            preserve_default=False,
        ),
    ]
